### ISSUE TITLE
[FEATURE] Add Lidarr support

### ISSUE THREAD

**Issue by luguber** [jghaanstra/tv.video.sonarr.radarr#8]
Can you add support for Lidarr?
https://lidarr.audio

**Comment by jghaanstra** [comment]
Could you be more explicit in what action cards you would like to see?

**Comment by luguber** [comment]
I was thinking pretty much the same as with Sonarr, just replace series with artist, and episode with album.

**Comment by jghaanstra** [comment]
Well, turns out the Lidarr API is pretty limited. There is no way to add new albums or artists to the download queue as far as I can tell looking at the documentation.

So integration with Lidarr will only be two triggers (notification when grabbing an album started and notification when album has been downloaded).

**Comment by luguber** [comment]
Ah ok, well I appreciate what I can get. But if you feel it's too much work for not so much gain then you don't need to bother. I apperciate the effor in anycase.

**Comment by jghaanstra** [comment]
Basic notification support for Lidarr has been added with release 2.1.0 which is pending approval in the app store.
